// <auto-generated />
using System;
using HealthBridge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthBridge.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthBridge.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailableDays")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AvailableTime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("ConsultationFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Hospital")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("HospitalBranch")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerifiedConsultant")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Qualifications")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HospitalBranch");

                    b.HasIndex("Specialization");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.DoctorAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppointmentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ConsultationFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("DoctorSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PatientAddress")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PatientNic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PatientPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("ServiceCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentNumber")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("DoctorSessionId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("DoctorAppointments");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.DoctorSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentBookings")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("SessionTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId", "SessionDate", "SessionTime")
                        .IsUnique();

                    b.ToTable("DoctorSessions");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.EMR.ChannelingAppointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppointmentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentDate");

                    b.HasIndex("PatientCode");

                    b.HasIndex("PatientId");

                    b.ToTable("ChannelingAppointments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1111111-1111-1111-1111-111111111111"),
                            AppointmentCode = "APT-3011",
                            AppointmentDate = new DateTime(2026, 8, 24, 10, 30, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 8, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorName = "Dr. Sarah Jenkins",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Room = "Room 304, West Wing",
                            Specialty = "Cardiologist",
                            Status = "Upcoming"
                        },
                        new
                        {
                            Id = new Guid("e2222222-2222-2222-2222-222222222222"),
                            AppointmentCode = "APT-2890",
                            AppointmentDate = new DateTime(2026, 7, 22, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 7, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorName = "Dr. Michael Chang",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Room = "Room 108, Main Clinic",
                            Specialty = "General Practitioner",
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("HealthBridge.Api.Models.EMR.ConsultationNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClinicalNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ConsultationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorDesignation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrescribedMedicines")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecommendedTests")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationDate");

                    b.HasIndex("PatientCode");

                    b.HasIndex("PatientId");

                    b.ToTable("ConsultationNotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            ClinicalNotes = "Patient presented with mild morning headaches and recorded BP 142/92 mmHg over 3 consecutive clinic visits. Denies chest pain, palpitation, or dyspnea. Advised DASH diet, sodium restriction < 2g/day, and routine aerobic exercise. Follow-up in 4 weeks.",
                            ConsultationDate = new DateTime(2026, 8, 10, 10, 30, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 8, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            Diagnosis = "Stage 1 Essential Hypertension with sinus rhythm",
                            DoctorDesignation = "Senior Consultant Cardiologist",
                            DoctorId = "DOC-101",
                            DoctorName = "Dr. Sarah Chen",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PrescribedMedicines = "[{\"name\":\"Lisinopril\",\"dosage\":\"10mg once daily in morning\",\"duration\":\"30 Days\"},{\"name\":\"Amlodipine\",\"dosage\":\"5mg once daily\",\"duration\":\"30 Days\"}]",
                            RecommendedTests = "Complete Blood Count (CBC), Lipid Panel, Resting ECG",
                            Status = "Completed",
                            UpdatedAt = new DateTime(2026, 8, 10, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            ClinicalNotes = "Occasional nocturnal dry cough following high pollen exposure. Spirometry showed FEV1 84% predicted, fully responsive to bronchodilators. Avoid known triggers.",
                            ConsultationDate = new DateTime(2026, 7, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 7, 18, 14, 30, 0, 0, DateTimeKind.Utc),
                            Diagnosis = "Mild Seasonal Allergic Asthma exacerbation",
                            DoctorDesignation = "Consultant Pulmonologist",
                            DoctorId = "DOC-102",
                            DoctorName = "Dr. Michael Chang",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PrescribedMedicines = "[{\"name\":\"Salbutamol (Ventolin) Inhaler\",\"dosage\":\"2 puffs as needed for wheeze\",\"duration\":\"As needed\"}]",
                            RecommendedTests = "Chest X-Ray, Total Serum IgE",
                            Status = "Completed",
                            UpdatedAt = new DateTime(2026, 7, 18, 14, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HealthBridge.Api.Models.EMR.EMRAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("Timestamp");

                    b.ToTable("EMRAuditLogs");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.EMR.LabReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<string>("OrderedDoctor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultsSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientCode");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("LabReports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Category = "Haematology",
                            CreatedAt = new DateTime(2026, 8, 11, 9, 30, 0, 0, DateTimeKind.Utc),
                            FileName = "CBC_Report_PAT1001.pdf",
                            FileUrl = "/uploads/reports/CBC_PAT1001.pdf",
                            OrderedDoctor = "Dr. Sarah Chen",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ReportDate = new DateTime(2026, 8, 11, 9, 15, 0, 0, DateTimeKind.Utc),
                            ResultsSummary = "WBC: 6.8 x10^3/uL (Normal), RBC: 4.9 x10^6/uL, Hemoglobin: 14.8 g/dL, Platelets: 240 x10^3/uL. Indices within normal physiological limits.",
                            Status = "Completed",
                            TestTitle = "Complete Blood Count (CBC)",
                            UpdatedAt = new DateTime(2026, 8, 11, 9, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Category = "Biochemistry",
                            CreatedAt = new DateTime(2026, 8, 11, 9, 45, 0, 0, DateTimeKind.Utc),
                            FileName = "Lipid_Profile_PAT1001.pdf",
                            FileUrl = "/uploads/reports/Lipid_PAT1001.pdf",
                            OrderedDoctor = "Dr. Sarah Chen",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ReportDate = new DateTime(2026, 8, 11, 9, 20, 0, 0, DateTimeKind.Utc),
                            ResultsSummary = "Total Cholesterol: 185 mg/dL (Normal < 200), HDL: 48 mg/dL, LDL: 112 mg/dL, Triglycerides: 125 mg/dL.",
                            Status = "Completed",
                            TestTitle = "Fasting Lipid Profile",
                            UpdatedAt = new DateTime(2026, 8, 11, 9, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Category = "Cardiology",
                            CreatedAt = new DateTime(2026, 8, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            OrderedDoctor = "Dr. Sarah Chen",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ReportDate = new DateTime(2026, 8, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            ResultsSummary = "Specimen collected; awaiting cardiologist interpretation signature.",
                            Status = "Pending",
                            TestTitle = "Resting 12-Lead Electrocardiogram (ECG)",
                            UpdatedAt = new DateTime(2026, 8, 15, 11, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HealthBridge.Api.Models.EMR.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ChronicConditions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("PatientCode")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Address = "742 Evergreen Terrace, Springfield",
                            Allergies = "Penicillin, Peanuts",
                            BloodGroup = "O+",
                            ChronicConditions = "Stage 1 Hypertension, Mild Asthma",
                            ContactPhone = "+1 555-0192",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1985, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john.anderson@example.com",
                            EmergencyContactName = "Mary Anderson (Spouse)",
                            EmergencyContactPhone = "+1 555-0193",
                            FullName = "John Anderson",
                            Gender = "Male",
                            PatientCode = "PAT-1001",
                            UpdatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Address = "120 Elm Street, Dallas",
                            Allergies = "Sulfa antibiotics",
                            BloodGroup = "A+",
                            ChronicConditions = "Type 2 Diabetes Mellitus",
                            ContactPhone = "+1 555-0284",
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria.garcia@example.com",
                            EmergencyContactName = "Carlos Garcia (Brother)",
                            EmergencyContactPhone = "+1 555-0285",
                            FullName = "Maria Garcia",
                            Gender = "Female",
                            PatientCode = "PAT-1002",
                            UpdatedAt = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Address = "88 Pine Avenue, Seattle",
                            Allergies = "None reported",
                            BloodGroup = "B+",
                            ChronicConditions = "Hyperlipidemia",
                            ContactPhone = "+1 555-0371",
                            CreatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1968, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "robert.kim@example.com",
                            EmergencyContactName = "Susan Kim (Daughter)",
                            EmergencyContactPhone = "+1 555-0372",
                            FullName = "Robert Kim",
                            Gender = "Male",
                            PatientCode = "PAT-1003",
                            UpdatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HealthBridge.Api.Models.EMR.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrescribedDoctor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientCode");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 8, 10, 11, 15, 0, 0, DateTimeKind.Utc),
                            Dosage = "Take 1 tablet by mouth daily in the morning with water",
                            Duration = "30 Days",
                            EndDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            MedicationName = "Lisinopril 10mg",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PrescribedDoctor = "Dr. Sarah Chen",
                            StartDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UnitPrice = 12.50m,
                            UpdatedAt = new DateTime(2026, 8, 10, 11, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 8, 10, 11, 15, 0, 0, DateTimeKind.Utc),
                            Dosage = "Take 1 tablet daily with or without food",
                            Duration = "30 Days",
                            EndDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            MedicationName = "Amlodipine 5mg",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PrescribedDoctor = "Dr. Sarah Chen",
                            StartDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UnitPrice = 10.00m,
                            UpdatedAt = new DateTime(2026, 8, 10, 11, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            Dosage = "Take 1 capsule every 8 hours for 7 days",
                            Duration = "7 Days",
                            EndDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            MedicationName = "Amoxicillin 500mg",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PrescribedDoctor = "Dr. Michael Chang",
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Completed",
                            UnitPrice = 15.00m,
                            UpdatedAt = new DateTime(2026, 6, 8, 15, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HealthBridge.Api.Models.LabBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AIConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<string>("AIExtractedDoctorName")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("AIPrescriptionDate")
                        .HasColumnType("date");

                    b.Property<string>("AIVerification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AIVerificationNotes")
                        .HasColumnType("text");

                    b.Property<string>("AgentWorkflowStateJson")
                        .HasColumnType("text");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric");

                    b.Property<int>("AssignedChairNo")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimatedServiceDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedWaitMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("LabTestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrescriptionImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("PriorityTier")
                        .HasColumnType("text");

                    b.Property<string>("QueueToken")
                        .HasColumnType("text");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("text");

                    b.Property<string>("ResultFileUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResultsUploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechnicianNotes")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("TimeSlot")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LabTestId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("LabBookings");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.LabTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TurnaroundDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("LabTests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Haematology",
                            CreatedAt = new DateTime(2026, 9, 23, 15, 20, 12, 777, DateTimeKind.Utc).AddTicks(653),
                            Description = "Measures different components of blood including red/white cells and platelets.",
                            IsActive = true,
                            IsRestricted = false,
                            Name = "Complete Blood Count (CBC)",
                            Price = 1500m,
                            TurnaroundDays = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Biochemistry",
                            CreatedAt = new DateTime(2026, 9, 23, 15, 20, 12, 777, DateTimeKind.Utc).AddTicks(668),
                            Description = "Measures cholesterol and triglyceride levels in the blood.",
                            IsActive = true,
                            IsRestricted = true,
                            Name = "Lipid Panel",
                            Price = 2500m,
                            TurnaroundDays = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "Biochemistry",
                            CreatedAt = new DateTime(2026, 9, 23, 15, 20, 12, 777, DateTimeKind.Utc).AddTicks(672),
                            Description = "Measures blood sugar levels after an 8-hour fast.",
                            IsActive = true,
                            IsRestricted = false,
                            Name = "Blood Glucose Fasting",
                            Price = 500m,
                            TurnaroundDays = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "Endocrinology",
                            CreatedAt = new DateTime(2026, 9, 23, 15, 20, 12, 777, DateTimeKind.Utc).AddTicks(675),
                            Description = "Evaluates thyroid gland function (TSH, T3, T4).",
                            IsActive = true,
                            IsRestricted = true,
                            Name = "Thyroid Function Test (TFT)",
                            Price = 3500m,
                            TurnaroundDays = 2
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "Microbiology",
                            CreatedAt = new DateTime(2026, 9, 23, 15, 20, 12, 777, DateTimeKind.Utc).AddTicks(692),
                            Description = "Analyses physical, chemical and microscopic properties of urine.",
                            IsActive = true,
                            IsRestricted = false,
                            Name = "Urine Full Report (UFR)",
                            Price = 800m,
                            TurnaroundDays = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Category = "Radiology",
                            CreatedAt = new DateTime(2026, 9, 23, 15, 20, 12, 777, DateTimeKind.Utc).AddTicks(695),
                            Description = "Imaging of lungs, heart and chest wall.",
                            IsActive = true,
                            IsRestricted = true,
                            Name = "Chest X-Ray",
                            Price = 2000m,
                            TurnaroundDays = 1
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Category = "Biochemistry",
                            CreatedAt = new DateTime(2026, 9, 23, 15, 20, 12, 777, DateTimeKind.Utc).AddTicks(698),
                            Description = "Assesses liver health via enzyme and protein levels.",
                            IsActive = true,
                            IsRestricted = true,
                            Name = "Liver Function Test (LFT)",
                            Price = 3000m,
                            TurnaroundDays = 2
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Category = "Haematology",
                            CreatedAt = new DateTime(2026, 9, 23, 15, 20, 12, 777, DateTimeKind.Utc).AddTicks(713),
                            Description = "Detects inflammation in the body.",
                            IsActive = true,
                            IsRestricted = false,
                            Name = "ESR (Erythrocyte Sedimentation Rate)",
                            Price = 600m,
                            TurnaroundDays = 1
                        });
                });

            modelBuilder.Entity("HealthBridge.Api.Models.LabTimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentBookings")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Time")
                        .IsUnique();

                    b.ToTable("LabTimeSlots");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("boolean");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.PatientFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("PatientFeedbacks");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.PatientProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NicNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PatientProfiles");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CollectedByStaffId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.PharmacyOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("DaysSupply")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("PatientConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PrescriptionHash")
                        .HasColumnType("text");

                    b.Property<string>("PrescriptionImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("SafetyFlags")
                        .HasColumnType("text");

                    b.Property<string>("SafetyRecommendedAction")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SafetyRiskScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SafetyValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.ToTable("PharmacyOrders");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.PharmacyOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("integer");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("PharmacyOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PharmacyOrderId");

                    b.ToTable("PharmacyOrderItems");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.PrescriptionSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DoctorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrescriptionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PrescriptionCode")
                        .IsUnique();

                    b.ToTable("PrescriptionSubmissions");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Patient");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.DoctorAppointment", b =>
                {
                    b.HasOne("HealthBridge.Api.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthBridge.Api.Models.DoctorSession", "DoctorSession")
                        .WithMany()
                        .HasForeignKey("DoctorSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Doctor");

                    b.Navigation("DoctorSession");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.DoctorSession", b =>
                {
                    b.HasOne("HealthBridge.Api.Models.Doctor", "Doctor")
                        .WithMany("Sessions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.EMR.ChannelingAppointment", b =>
                {
                    b.HasOne("HealthBridge.Api.Models.EMR.Patient", "Patient")
                        .WithMany("ChannelingAppointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.EMR.ConsultationNote", b =>
                {
                    b.HasOne("HealthBridge.Api.Models.EMR.Patient", "Patient")
                        .WithMany("ConsultationNotes")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.EMR.LabReport", b =>
                {
                    b.HasOne("HealthBridge.Api.Models.EMR.Patient", "Patient")
                        .WithMany("LabReports")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.EMR.Prescription", b =>
                {
                    b.HasOne("HealthBridge.Api.Models.EMR.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.LabBooking", b =>
                {
                    b.HasOne("HealthBridge.Api.Models.LabTest", "LabTest")
                        .WithMany("Bookings")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabTest");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.Medicine", b =>
                {
                    b.HasOne("HealthBridge.Api.Models.Category", "Category")
                        .WithMany("Medicines")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.PatientProfile", b =>
                {
                    b.HasOne("HealthBridge.Api.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("HealthBridge.Api.Models.PatientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.PharmacyOrder", b =>
                {
                    b.HasOne("HealthBridge.Api.Models.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.PharmacyOrderItem", b =>
                {
                    b.HasOne("HealthBridge.Api.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthBridge.Api.Models.PharmacyOrder", "PharmacyOrder")
                        .WithMany("Items")
                        .HasForeignKey("PharmacyOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("PharmacyOrder");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.PrescriptionSubmission", b =>
                {
                    b.HasOne("HealthBridge.Api.Models.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.Category", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.EMR.Patient", b =>
                {
                    b.Navigation("ChannelingAppointments");

                    b.Navigation("ConsultationNotes");

                    b.Navigation("LabReports");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.LabTest", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HealthBridge.Api.Models.PharmacyOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
